#!/bin/bash
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 25
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 24
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 23
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 22
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 21
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 20
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 19
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 18
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 17
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 16
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 15
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 14
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 13
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 12
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 11
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 10
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 9
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 8
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 7
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 6
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 5
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 4
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 3
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 2
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 1
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212002-carrefour --categoria 0

python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/214038-los3pollitos-mt-nc --categoria 1
python3 get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/214038-los3pollitos-mt-nc --categoria 0
