python3 get_data_nocat.py --comercio 0
python3 get_data_nocat.py --comercio 1
python3 get_data_nocat.py --comercio 2
python3 get_data_nocat.py --comercio 3
python3 get_data_nocat.py --comercio 4
python3 get_data_nocat.py --comercio 5
python3 get_data_nocat.py --comercio 6
python3 get_data_nocat.py --comercio 7
python3 get_data_nocat.py --comercio 8
python3 get_data_nocat.py --comercio 9
python3 get_data_nocat.py --comercio 10
python3 get_data_nocat.py --comercio 11
python3 get_data_nocat.py --comercio 12
python3 get_data_nocat.py --comercio 13
python3 get_data_nocat.py --comercio 14
python3 get_data_nocat.py --comercio 15
python3 get_data_nocat.py --comercio 16
python3 get_data_nocat.py --comercio 17
python3 get_data_nocat.py --comercio 18
python3 get_data_nocat.py --comercio 19
python3 get_data_nocat.py --comercio 20
python3 get_data_nocat.py --comercio 21