python get_data_nocat.py --comercio 0
python get_data_nocat.py --comercio 1
python get_data_nocat.py --comercio 2
python get_data_nocat.py --comercio 3
python get_data_nocat.py --comercio 4
python get_data_nocat.py --comercio 5
python get_data_nocat.py --comercio 6
python get_data_nocat.py --comercio 7
python get_data_nocat.py --comercio 8
python get_data_nocat.py --comercio 9
python get_data_nocat.py --comercio 10
python get_data_nocat.py --comercio 11
python get_data_nocat.py --comercio 12
python get_data_nocat.py --comercio 13
python get_data_nocat.py --comercio 14
python get_data_nocat.py --comercio 15
python get_data_nocat.py --comercio 16
python get_data_nocat.py --comercio 17
python get_data_nocat.py --comercio 18
python get_data_nocat.py --comercio 19
python get_data_nocat.py --comercio 20
python get_data_nocat.py --comercio 21
