python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 25
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 24
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 23
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 22
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 21
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 20
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 19
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 18
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 17
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 16
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 15
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 14
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 13
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 12
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 11
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 10
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 9
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 8
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 7
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 6
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 5
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 4
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 3
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 2
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 1
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/212819-vea --categoria 0

python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/214038-los3pollitos-mt-nc --categoria 1
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/214038-los3pollitos-mt-nc --categoria 0