python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 0
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 1
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 2
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 3
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 4
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 5
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 6
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 7
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 8
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 9
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 10
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 11
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 12
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 13
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 14
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 15
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 16
python get_data_cat.py --comercio https://www.rappi.com.ar/tiendas/210686-simplicity-market --categoria 17